name: bus_locator
description: "Application de localisation des arrêts de bus."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.0.0

  # Carte et géolocalisation
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0

  # Requêtes HTTP vers Spring Boot
  dio: ^5.4.0

  # Stockage local (token JWT)
  flutter_secure_storage: ^9.0.0

  # Icônes
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true